version: '3.5'

services:

    simple-web-service-2:
      image: devopsdockeruh/simple-web-service
      build: .
      container_name: simple-web-service-2
      ports:
        - 8080:8080
      command: -p 8080:8080 server
