version: '3.5'

services:
  backend:
    image: backend-project
    build: .
    container_name: backend_test
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=asd
      - POSTGRES_PASSWORD=postgres
    #ports:
    #  - 8080:8080
    command: ./server

  frontend:
    image: frontend-project
    build: .
    container_name: frontend_test
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080
    #ports:
    #  - 5000:5000
    command: serve -s -l 5000 build

  redis:
    image: redis

  db:
    image: postgres
    environment:
      - POSTGRES_USER=asd
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db

  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
